project:
  type: website
  output-dir: docs

website:
  title: "G.R. van der Ploeg"
  navbar:
    right:
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



