project:
  type: website
  output-dir: docs

website:
  title: "Roel van der Ploeg"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



