---
title: "Presentations"
format: html
editor: visual
---

## 2025

-   **van der Ploeg, G. R.**, Heintz-Buschart A., Westerhuis, J. A., Smilde, A. K., "Unraveling Host-Microbiome-Dynamics: Powering Discovery with Multi-Way Analysis", *Poster presentation*, Amsterdam Microbiome Expertise Center (AMEC) Day 2025, February 13, Amsterdam, the Netherlands. [Link to the poster](https://bsky.app/profile/grvanderploeg.bsky.social/post/3li3gdgryoo2m)
-   **van der Ploeg, G. R.,** "Microbiome data analysis using multi-way methods", *Oral presentation*, RPA-PMH Microbiome Friday, April 3, Amsterdam, the Netherlands.
-   **van der Ploeg, G. R.,** Westerhuis, J. A., Heintz-Buschart A., Smilde, A. K.,"Microbiome data analysis using multi-way methods", *Oral presentation*, BioSB, May 20-21, Baarlo, the Netherlands.
-   **van der Ploeg, G. R.**, White, F. T. G., Westerhuis, J. A., Heintz-Buschart A., Smilde, A. K., "ACMTF-R: multi-way data fusion using biological variation of interest", *Oral presentation*, TRICAP2025, June 23-27, Alesund, Norway.

## 2024

-   **van der Ploeg, G.R. & White, F. T. G.**, "Describing common and distinct variation in multi-omics studies", *Invited oral presentation*, TrACEr workshop, April 22-23, Oslo, Norway.
-   **van der Ploeg, G. R.**, "parafac4microbiome: Exploratory analysis of longitudinal microbiome data using Parallel Factor Analysis", *Oral presentation*, BioSB, May 18-19, Egmond aan Zee, the Netherlands.

## 2023

-   **van der Ploeg, G. R.**, "High-level integration of longitudinal oral microbiome and metabolome data finds pathways important to induced gingivitis", *Oral presentation*, BioSB, May 9-10, Egmond aan Zee, the Netherlands.\
-   **van der Ploeg, G. R.**, van der Veen, M. H., Keijser, B. J. F., Zaura, E., Heintz-Buschart A., Westerhuis, J. A., Smilde, A. K., "Multi-omics data integration identifies oral-o-types and pathways important to induced gingivitis", *Poster presentation*, SILS Research Day, June 29, Amsterdam, the Netherlands.

## 2022

-   **van der Ploeg, G. R.**, "Data integration of oral microbiome and metabolome data using PARAFAC", *Oral presentation*, Dutch Chemometrics Society, April 1, Online.
-   **van der Ploeg, G. R.**, "Data integration of oral microbiome and metabolome data using PARAFAC", *Oral presentation*, SILS Research Day, June 21, Amsterdam, the Netherlands.
-   **van der Ploeg, G. R.**, Heintz-Buschart A., Westerhuis, J. A., Smilde, A. K., "Data integration of oral microbiome and metabolome using PARAFAC", *Poster presentation*, BioSB, June 28-29, Lunteren, the Netherlands.
-   **van der Ploeg, G. R.**, "Modelling the development of gingivitis", *Oral presentation*, Path Modelling Workshop, 25-26 April, Zaandam, the Netherlands.
